// Helper for serving local /public assets through Cloudinary.
// The manifest is generated by `scripts/upload-to-cloudinary.mjs` and maps
// each historical URL path (e.g. "/media/shopfront.jpg") to its Cloudinary
// asset. `cldUrl()` returns a CDN URL with auto-format + auto-quality so
// existing <img>, <video>, <audio>, poster=, and CSS url() callsites only need
// to wrap their string.

import manifest from "./cld-manifest.json";

type AssetKind = "image" | "video" | "raw";
type ManifestEntry = {
  kind: AssetKind;
  publicId: string;
  ext: string;
  width?: number;
  height?: number;
};
type Manifest = {
  cloudName: string;
  folder: string;
  assets: Record<string, ManifestEntry>;
};

const m = manifest as unknown as Manifest;

function normalize(localPath: string): string {
  try {
    return decodeURIComponent(localPath);
  } catch {
    return localPath;
  }
}

export function cldAsset(localPath: string): ManifestEntry | null {
  return m.assets[normalize(localPath)] ?? null;
}

type UrlOpts = {
  // Cloudinary transformation segment, e.g. "w_800,c_fill,g_auto".
  // f_auto/q_auto are applied automatically for image+video.
  transform?: string;
  // Overrides the default q_auto, e.g. "q_auto:best" for hero media where
  // compression artefacts would show. Ignored for raw assets.
  quality?: string;
};

export function cldUrl(localPath: string, opts: UrlOpts = {}): string {
  const entry = cldAsset(localPath);
  if (!entry) return localPath; // fall back to /public during dev/migration
  const base = `https://res.cloudinary.com/${m.cloudName}`;
  const transforms: string[] = [];
  if (entry.kind !== "raw") transforms.push("f_auto", opts.quality ?? "q_auto");
  if (opts.transform) transforms.push(opts.transform);
  const tx = transforms.length ? `${transforms.join(",")}/` : "";
  return `${base}/${entry.kind}/upload/${tx}${entry.publicId}${entry.ext}`;
}

// CSS background-image helper — wraps the URL in url(...) and escapes quotes.
export function cldCss(localPath: string, opts?: UrlOpts): string {
  return `url("${cldUrl(localPath, opts).replace(/"/g, '\\"')}")`;
}
